Disable unused function for now.
This fix :

../libg15.c:878:22: error: 'g15KeyToLogitechKeyCode' defined but not used [-Werror=unused-function]
 static unsigned char g15KeyToLogitechKeyCode(int key)
                      ^