Fix unused variable 'interface'.
../libg15.c: In function 'findAndOpenDevice':
../libg15.c:158:9: error: unused variable 'interface' [-Werror=unused-variable]
     int interface=0;