Fix warnings unused variables i.
../libg15.c: In function 'processKeyEventG13':
../libg15.c:894:9: error: unused variable 'i' [-Werror=unused-variable]
     int i;
         ^
../libg15.c: In function 'processKeyEventG13Extended':
../libg15.c:966:9: error: unused variable 'i' [-Werror=unused-variable]
     int i;
         ^
../libg15.c: In function 'processG510AudioKeyEvent':
../libg15.c:1017:9: error: unused variable 'i' [-Werror=unused-variable]
     int i;
         ^
../libg15.c: In function 'processKeyEvent9Byte':
../libg15.c:1035:9: error: unused variable 'i' [-Werror=unused-variable]
     int i;
         ^
../libg15.c: In function 'processKeyEvent5Byte':
../libg15.c:1126:9: error: unused variable 'i' [-Werror=unused-variable]
     int i;
         ^
../libg15.c: In function 'processKeyEvent4Byte':
../libg15.c:1274:6: error: unused variable 'i' [-Werror=unused-variable]
  int i;
      ^